const RESPONSE_TITLE = Object.freeze({
  OK: "OK",
  CREATED: "CREATED",
  UPDATED: "UPDATED",
  DELETED: "DELETED",
  BAD_REQUEST: "BAD_REQUEST",
  NOT_ALLOWED: "NOT_ALLOWED",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  UNAUTHORIZED: "UNAUTHORIZED",
});

export default RESPONSE_TITLE;
